# WireSentinel dependency license policy.
# Bundled GPL/LGPL binaries (sing-box, WinDivert) are subprocess/DLL-only — not Rust deps.

[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "0BSD",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "Unicode-3.0",
  "MPL-2.0",
  "OpenSSL",
  "Unlicense",
]
confidence-threshold = 0.8
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
