# Generate WiX and NSIS fragments for third-party binaries staged under installer/staging/bin.
# Usage: .\scripts\generate-installer-third-party.ps1 -Arch x64

param(
    [ValidateSet("x64", "arm64")]
    [string]$Arch = "x64"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$StageDir = Join-Path $Root "installer\staging\bin"
$GenDir = Join-Path $Root "installer\generated"
$WixPath = Join-Path $GenDir "third-party.wxs"
$NsisPath = Join-Path $GenDir "third-party-files.nsh"

if (-not (Test-Path $StageDir)) {
    throw "Missing installer staging directory: $StageDir (run Stage-InstallerBinaries first)"
}

New-Item -ItemType Directory -Force -Path $GenDir | Out-Null

$BinaryFiles = @(
    @{ Name = "sing-box.exe"; Id = "SingBoxExe"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567003" },
    @{ Name = "tor.exe"; Id = "TorExe"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567004" }
)
if ($Arch -eq "x64") {
    $BinaryFiles = @(
        @{ Name = "WinDivert.dll"; Id = "WinDivertDll"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567001" },
        @{ Name = "WinDivert64.sys"; Id = "WinDivertSys"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567002" }
    ) + $BinaryFiles
}

$LicenseFiles = @(
    @{ Name = "MIT.txt"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567010" },
    @{ Name = "LGPL-3.0.txt"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567011" },
    @{ Name = "GPL-3.0.txt"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567012" },
    @{ Name = "BSD-3-Clause-Tor.txt"; Guid = "f1a2b3c4-d5e6-7890-abcd-ef1234567013" }
)

$presentBinaries = @()
foreach ($entry in $BinaryFiles) {
    $path = Join-Path $StageDir $entry.Name
    if (Test-Path $path) {
        $presentBinaries += $entry
    }
}

$noticesPath = Join-Path $StageDir "THIRD_PARTY_NOTICES.txt"
$licensesDir = Join-Path $StageDir "licenses"
$presentLicenses = @()
if (Test-Path $licensesDir) {
    foreach ($entry in $LicenseFiles) {
        $path = Join-Path $licensesDir $entry.Name
        if (Test-Path $path) {
            $presentLicenses += $entry
        }
    }
}

$wxs = @()
$wxs += '<?xml version="1.0" encoding="UTF-8"?>'
$wxs += '<!-- Generated by scripts/generate-installer-third-party.ps1; do not edit. -->'
$wxs += '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">'
$wxs += '  <Fragment>'

if ($presentLicenses.Count -gt 0 -or (Test-Path $noticesPath)) {
    $wxs += '    <DirectoryRef Id="INSTALLFOLDER">'
    $wxs += '      <Directory Id="LicensesDir" Name="licenses" />'
    $wxs += '    </DirectoryRef>'
}

if ($presentBinaries.Count -gt 0) {
    $wxs += '    <ComponentGroup Id="ThirdPartyComponents" Directory="INSTALLFOLDER">'
    foreach ($entry in $presentBinaries) {
        $wxs += "      <Component Id=`"$($entry.Id)`" Guid=`"$($entry.Guid)`">"
        $wxs += "        <File Source=`"..\..\installer\staging\bin\$($entry.Name)`" KeyPath=`"yes`" />"
        $wxs += '      </Component>'
    }
    $wxs += '    </ComponentGroup>'
}

if ((Test-Path $noticesPath) -or $presentLicenses.Count -gt 0) {
    $wxs += '    <ComponentGroup Id="LegalNoticesComponents">'
    if (Test-Path $noticesPath) {
        $wxs += '      <Component Id="ThirdPartyNotices" Guid="f1a2b3c4-d5e6-7890-abcd-ef1234567005" Directory="INSTALLFOLDER">'
        $wxs += '        <File Source="..\..\installer\staging\bin\THIRD_PARTY_NOTICES.txt" KeyPath="yes" />'
        $wxs += '      </Component>'
    }
    foreach ($entry in $presentLicenses) {
        $id = ($entry.Name -replace '[^A-Za-z0-9]', '')
        $wxs += "      <Component Id=`"License_$id`" Guid=`"$($entry.Guid)`" Directory=`"LicensesDir`">"
        $wxs += "        <File Source=`"..\..\installer\staging\bin\licenses\$($entry.Name)`" KeyPath=`"yes`" />"
        $wxs += '      </Component>'
    }
    $wxs += '    </ComponentGroup>'
}

$wxs += '  </Fragment>'
$wxs += '</Wix>'
$wxs | Set-Content -Path $WixPath -Encoding UTF8

#region agent log
try {
    $debugLog = Join-Path $Root ".cursor\debug-28de1e.log"
    $rootName = ([xml]($wxs -join "`n")).DocumentElement.LocalName
    $logEntry = @{
        sessionId    = "28de1e"
        hypothesisId = "H1"
        location     = "generate-installer-third-party.ps1"
        message      = "third-party.wxs document root"
        data         = @{ documentRoot = $rootName; arch = $Arch; binaryCount = $presentBinaries.Count }
        timestamp    = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
        runId        = "post-fix"
    } | ConvertTo-Json -Compress
    Add-Content -Path $debugLog -Value $logEntry -Encoding UTF8
} catch {
    # debug logging must not break installer generation
}
#endregion

$nsis = @()
$nsis += '; Generated by scripts/generate-installer-third-party.ps1; do not edit.'
$nsis += ''
$nsis += '!macro InstallThirdPartyFiles'
foreach ($entry in $presentBinaries) {
    $nsis += "  File `"..\..\installer\staging\bin\$($entry.Name)`""
}
if (Test-Path $noticesPath) {
    $nsis += '  File "..\..\installer\staging\bin\THIRD_PARTY_NOTICES.txt"'
}
if ($presentLicenses.Count -gt 0) {
    $nsis += '  SetOutPath "$INSTDIR\licenses"'
    foreach ($entry in $presentLicenses) {
        $nsis += "  File `"..\..\installer\staging\bin\licenses\$($entry.Name)`""
    }
    $nsis += '  SetOutPath "$INSTDIR"'
}
$nsis += '!macroend'
$nsis += ''
$nsis += '!macro UninstallThirdPartyFiles'
foreach ($entry in $presentBinaries) {
    $nsis += "  Delete `"`$INSTDIR\$($entry.Name)`""
}
if (Test-Path $noticesPath) {
    $nsis += '  Delete "$INSTDIR\THIRD_PARTY_NOTICES.txt"'
}
if ($presentLicenses.Count -gt 0) {
    foreach ($entry in $presentLicenses) {
        $nsis += "  Delete `"`$INSTDIR\licenses\$($entry.Name)`""
    }
    $nsis += '  RMDir "$INSTDIR\licenses"'
}
$nsis += '!macroend'

$nsis | Set-Content -Path $NsisPath -Encoding UTF8

Write-Host "Generated installer third-party fragments ($Arch):"
Write-Host "  Binaries: $($presentBinaries.Name -join ', ')"
Write-Host "  Legal: THIRD_PARTY_NOTICES=$([bool](Test-Path $noticesPath)), licenses=$($presentLicenses.Count)"
Write-Host "  WiX: $WixPath"
Write-Host "  NSIS: $NsisPath"
